### ISSUE TITLE
Where is the link for the Online Demo Server ????

### ISSUE THREAD

**Issue by rcemper** [danb7788/fhir-patient-viewer#1]
You have a link for a video.
But this is not an Online Demo Server where you can type and operate yourself.

**Comment by danb7788** [comment]
Hey! For setting up a sandbox FHIR server you can follow these instructions: https://gettingstartedhealth.intersystems.com/standards-quickstarts/fhir-quickstart/

I initially included a live demo of the viewer on a GitHub pages repo, but the problem is the InsterSystems sandbox FHIR server providing the data is only up for 3 days each time you launch it. I thought it was better to just include the video with instructions for setting up your own sandbox and then testing the FHIR Patient Viewer in your localhost.
